jwt:
  key: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}
refresh-token:
  expiration: ${JWT_REFRESH_EXPIRATION_MS}
  key: ${JWT_REFRESH_SECRET}

facebook:
  client-id: ${FACEBOOK_CLIENT_ID}
  client-secret: ${FACEBOOK_CLIENT_SECRET}
  redirect-uri: ${FACEBOOK_REDIRECT_URI}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}


spring:
  application:
    name: ecommerce-fashion
#  elasticsearch:
#    uris: ${ELASTICSEARCH_URL}


  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/ecommerce-fashion
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        type:
          jsonb: com.vladmihalcea.hibernate.type.json.JsonBinaryType
        dialect: org.hibernate.dialect.PostgreSQLDialect
        register-types: auto


server:
  port: ${PORT_SERVER}



