jwt:
  key: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}
refresh-token:
  expiration: ${JWT_REFRESH_EXPIRATION_MS}
  key: ${JWT_REFRESH_SECRET}

facebook:
  client-id: ${FACEBOOK_CLIENT_ID}
  client-secret: ${FACEBOOK_CLIENT_SECRET}
  redirect-uri: ${FACEBOOK_REDIRECT_URI}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${GOOGLE_REDIRECT_URI}


minio:
  endpoint: ${MINIO_ENDPOINT}
  access:
    key: ${MINIO_ACCESS_KEY}
  secret:
    key: ${MINIO_SECRET_KEY}
  bucket:
    name: ${MINIO_BUCKET_NAME}


spring:
  application:
    name: ecommerce-fashion
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}


  server:
    port: ${PORT_SERVER}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/ecommerce-fashion
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      format-sql: true

    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        type:
          jsonb: com.vladmihalcea.hibernate.type.json.JsonBinaryType
        dialect: org.hibernate.dialect.PostgreSQLDialect
        register-types: auto

  mail:
    host: smtp.gmail.com
    port: 587
    username: thuquyen01012004@gmail.com
    password: ywyevbxuvxyzjneg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  quartz:
    job:
      store:
        type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount:5
#mailgun:
#  apiKey: 1ca13d6dd4d32530a327dab7519b8097-2b91eb47-3b79f8c3
#  domain: sandboxd33d1c65feb7420282cf794cefdc8a8c.mailgun.org



