CREATE TABLE products.origin
(
    id        BIGSERIAL PRIMARY KEY,
    name      VARCHAR(50) NOT NULL,
    create_at TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_by BIGINT NOT NULL ,
    update_by BIGINT,
    deleted   BOOLEAN DEFAULT FALSE
);