name: Notify Telegram on Commit

on:
  push:
    branches:
      - '**'  

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get commit details
        id: commit-info
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          COMMIT_AUTHOR_NAME=$(git log -1 --pretty=%an)
          COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          COMMIT_DATE=$(TZ='Asia/Ho_Chi_Minh' date +'%Y-%m-%d %H:%M:%S %Z')
          echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR_NAME=${COMMIT_AUTHOR_NAME}" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR_EMAIL=${COMMIT_AUTHOR_EMAIL}" >> $GITHUB_ENV
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
          echo "COMMIT_DATE=${COMMIT_DATE}" >> $GITHUB_ENV

      - name: Send notification to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot7002498142:AAEjxsMSEIRjomBxKOEDgCrlTWURA6H3nU8/sendMessage \
            -d chat_id=1828497602 \
            -d text="New commit to repository: ${GITHUB_REPOSITORY}%0ABranch: ${BRANCH_NAME}%0ACommit message: ${COMMIT_MESSAGE}%0AAuthor: ${COMMIT_AUTHOR_NAME} <${COMMIT_AUTHOR_EMAIL}>%0ADate: ${COMMIT_DATE}"